---
title: "707Wine_Benji_YLtry"
output: html_notebook
---
```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(glmnet)
library(gbm)
library(gam)
library(stringr)
library(xgboost)
library(caret)
library(Matrix)
library(e1071)
library(liquidSVM)
```

```{r}
# read data
read_csv("Data/wine-reviews/winemag-data-130k-v2.csv") %>% select(-X1) %>% unique -> data
```

```{r}
# preprocessing
scale_taster <- function(points){
    # takes a vector of numbers, subtracts every element by the mean of the vector, and then
    # divides every element by the standard deviation of the vector
    
    return((points - mean(points, na.rm = TRUE)) / sd(points, na.rm = TRUE))
}

percentile_taster <- function(x){
    # takes a vector of numbers, ranks every element and divides by n, giving the percentile of each element
    trunc(rank(x))/length(x) * 100
}

data <- data %>% group_by(taster_name) %>% mutate("Scaled_Points" = scale_taster(points))

data <- data %>% group_by(taster_name) %>% mutate("Percentile_Points" = percentile_taster(points))

tab <- data %>% group_by(province) %>% summarize("Proportion" = n()/nrow(data))
tab <- tab[tab$Proportion > 0.01, ]

tabcountry <-  data %>% group_by(country) %>% summarize("Proportion" = n()/nrow(data))
tabcountry <- tabcountry[tabcountry$Proportion > 0.01, ]

data$country_other <- ifelse(data$country %in% tabcountry$country, 
                                paste0(data$country, "_other"), data$country)
data$location <- ifelse(data$province %in% tab$province, data$province,
                                     data$country_other)

year <- str_extract_all(data$title, "[1-2][09][0-9]{2}")

data$year <- lapply(year, function(x){
    x = x %>% as.numeric
  if(!all(is.na(x))){
    newx <- x[(x > 1900) & (x < 2018)]
    if (!all(is.na(newx))) {
      newx <- max(newx)
      return(newx)
    } else {
      return(NA)
    }
  } else {
    return(NA)
  }}) %>% unlist

data$location <- factor(data$location)
data$taster_name <- factor(data$taster_name)
data$taster_name <- addNA(data$taster_name)
data$title <- factor(data$title)
data$variety <- factor(data$variety)
data$region_1 <- factor(data$region_1)
data$region_2 <- factor(data$region_2)
data$country <- factor(data$country)
data$province <- factor(data$province)
data$winery <- factor(data$winery)
data$taster_twitter_handle <- factor(data$taster_twitter_handle)
data$designation <- factor(data$designation)
```

```{r}
# helper function
impute_mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
    # impute_mean replaces missing values with the average value of a group

clean <- function(df){
    # clean removes the varieties that only have missing prices, and are thus unimputable by our rule,
    # and then it imputes the remaining missing prices using the average price of that wine's variety
    
    df %>% group_by(variety) %>% summarize("Average_Price" = mean(price, na.rm = T), 
                                           "Count" = n()) %>% 
    filter(is.na(Average_Price)) %>% select(variety) %>% unlist() -> drop_variety 
    
    df %>% filter(!(variety %in% drop_variety)) -> sample2
    
    sample2 %>% group_by(variety) %>% mutate(price = impute_mean(price)) -> sample2
    
    sample2 <- sample2[complete.cases(sample2),]
    return(sample2)
}
```

```{r}
# check data
dim(data)
summary(data)
str(data)

data <- data %>% select(-country_other, -taster_twitter_handle, -description, -winery, -designation)
```

```{r}
# split train test
set.seed(2018)
train.index <- sample(2/3 * nrow(data))
train <- data[train.index,]
test <- data[-train.index,]
dim(train)
summary(train)
dim(test)
summary(test)
```


```{r}
# clean train
clean_train <- train[lapply(train, function(x) sum(is.na(x)) / length(x))  < 0.1]
clean_train <- clean(clean_train)
clean_train$`US_vs_non-US` <- factor(ifelse(clean_train$country == 'US', 'US', 'non-US'))
clean_train[is.na(clean_train$country), 'US_vs_non-US'] <- NA
clean_train$`US_vs_non-US` <- addNA(clean_train$`US_vs_non-US`)
#clean_train <- clean_train %>% select(-title, -country)
clean_train <- clean_train %>% select(-Scaled_Points, -Percentile_Points)
dim(clean_train)
```


```{r}
ggplot(aes(x=points, y=price, col = taster_name), data = clean_train) + geom_jitter()
ggplot(aes(x=points, y=price, col = `US_vs_non-US`), data = clean_train) + geom_jitter() + theme(legend.position = "right")
ggplot(aes(x=points, y=price, col = variety), data = clean_train) + geom_jitter() + theme(legend.position = 'none')
ggplot(aes(x=year, y=price, col=`US_vs_non-US`), data = clean_train) + geom_jitter()
ggplot(aes(x=year, y=points, col=`US_vs_non-US`), data = clean_train) + geom_jitter()
```
```{r}
# gam only: points and price
set.seed(2018)
k <- 10
sp <- split(c(1:nrow(train)), c(1:k))
price_pt_gam_error <- matrix(NA, nrow=k, ncol=2)
for(i in 1:k){
    cleanwine_train <- train[-sp[[i]], ]
    cleanwine_test <- train[sp[[i]], ]
    
    # data cleaning
    cleanwine_train <- cleanwine_train[lapply(cleanwine_train, function(x) sum(is.na(x)) / length(x))  < 0.1]
    cleanwine_train <- clean(cleanwine_train)
    cleanwine_train <- cleanwine_train %>% select(-title, -country)
    #print(colnames(cleanwine_train))
    #print(head(cleanwine_train))
    
    cleanwine_test <- cleanwine_test[lapply(cleanwine_test, function(x) sum(is.na(x)) / length(x))  < 0.1]
    cleanwine_test <- clean(cleanwine_test)
    cleanwine_test <- cleanwine_test %>% select(-title, -country, -province)
    #print(colnames(cleanwine_test))
    #print(head(cleanwine_test))
    
    # select only Percentile_Points and Price for gam
    #cleanwine_train_gam <- cleanwine_train %>% select(Percentile_Points, price)
    #cleanwine_test_gam <- cleanwine_test %>% select(Percentile_Points, price)   
    
    # gam
    price_gam <- gam(price ~ s(Percentile_Points), data = cleanwine_train)
    pt_gam <- gam(Percentile_Points ~ s(price), data = cleanwine_train)
    price_pred <- predict(price_gam, cleanwine_test)
    pt_pred <- predict(pt_gam, cleanwine_test)
    price_pt_gam_error[i,1] <- mean(abs(price_pred- cleanwine_test$price))
    price_pt_gam_error[i,2] <- mean((pt_pred - cleanwine_test$Percentile_Points)^2)
}
```

```{r}
price_pt_gam_error
```


```{r}
# CV on train
set.seed(2018)
k <- 10
sp <- createFolds(train$variety, k)
price_fold_error <- matrix(NA, nrow=k, ncol=5)
pt_fold_error <- matrix(NA, nrow=k, ncol=5)
for(i in 1:k){
    cleanwine_train <- train[-sp[[k]], ]
    cleanwine_test <- train[sp[[k]], ]
    
    # data cleaning
    cleanwine_train <- cleanwine_train[lapply(cleanwine_train, function(x) sum(is.na(x)) / length(x))  < 0.1]
    cleanwine_train <- clean(cleanwine_train)
    cleanwine_train <- cleanwine_train %>% select(-title, -country, -province)
    #print(colnames(cleanwine_train))
    
    cleanwine_test <- cleanwine_test[lapply(cleanwine_test, function(x) sum(is.na(x)) / length(x))  < 0.1]
    cleanwine_test <- clean(cleanwine_test)
    cleanwine_test <- cleanwine_test %>% select(-title, -country)
    #print(colnames(cleanwine_test))
    
    cleanwine_train <- cleanwine_train %>% select(-Scaled_Points, -Percentile_Points)
    train.data.price <- cleanwine_train %>% select(-price)
    #print(colnames(train.data.price))
    train.data.price <- sparse.model.matrix(~., train.data.price)[,-1]
    train.data.pt <- cleanwine_train %>% select(-points)
    train.data.pt <- sparse.model.matrix(~., train.data.pt)[,-1]
    
    cleanwine_test <- cleanwine_test %>% select(-Scaled_Points, -Percentile_Points)
    test.data.price <- cleanwine_test %>% select(-price)
    #print(colnames(test.data.price))
    test.data.price <- sparse.model.matrix(~., test.data.price)[,-1]
    #print(colnames(test.data.price))
    test.data.pt <- cleanwine_test %>% select(-points)
    test.data.pt <- sparse.model.matrix(~., test.data.pt)[,-1]
    
    # random forest
    subsamps <- seq(0.1, 1, 0.1)
    train_error_price <- vector("numeric", length(seq(0.1, 1, 0.1)))
    train_error_pt <- vector("numeric", length(seq(0.1, 1, 0.1)))
    
    for (j in 1:length(seq(0.1, 1, 0.1))) {
      rf_train_price <- xgboost(data = train.data.price, label=cleanwine_train$price, max_depth = 0, verbose = 0, num_parallel_tree = 1000, subsample = subsamps[i], nrounds = 1, colsample_bylevel=0.6, objective = "reg:linear", eval_metric = 'mae')
      rf_train_pt <- xgboost(data = train.data.pt, label=cleanwine_train$points, max_depth = 0, verbose = 0, num_parallel_tree = 1000, subsample = subsamps[i], nrounds = 1, colsample_bylevel=0.6, objective = "reg:linear", eval_metric = 'rmse')
      train_error_price[j] <- as.numeric(rf_train_price$evaluation_log[,2])
      train_error_pt[j] <- as.numeric(rf_train_pt$evaluation_log[,2])
    }
    index.min.price <- which.min(train_error_price)
    index.min.pt <- which.min(train_error_pt)
    
    rf_cleanwine_price <- xgboost(data = train.data.price, label=cleanwine_train$price, max_depth = 0, verbose = 0, num_parallel_tree = 1000, subsample = subsamps[index.min.price], nrounds = 1, colsample_bylevel=0.6, objective = "reg:linear", eval_metric = 'mae')
    #print(rf_cleanwine_price$feature_names)
    rf_cleanwine_pt <- xgboost(data = train.data.pt, label=cleanwine_train$points, max_depth = 0, verbose = 0, num_parallel_tree = 1000, subsample = subsamps[index.min.pt], nrounds = 1, colsample_bylevel=0.6, objective = "reg:linear", eval_metric = 'rmse')
    print(length(rf_cleanwine_pt$feature_names) == length(colnames(test.data.price)))

    test.pred.price <- predict(rf_cleanwine_price, test.data.price)
    price_fold_error[i, 1] <- mean(abs(cleanwine_test$price - test.pred.price))
    test.pred.pt <- predict(rf_cleanwine_pt, test.data.pt)                               
    pt_fold_error[i,1] <- mean((cleanwine_test$price - test.pred.pt)^2)
    
    # svm
    svm_cleanwine_price <- svm(price~., cleanwine_train)
    svm_cleanwine_pt <- svm(points~., cleanwine_train)
    result_price <- test(svm_cleanwine_price, cleanwine_test)
    price_fold_error[i,2] <- mean(abs(cleanwine_test$price - result_price))

    result_pt <- test(svm_cleanwine_pt, cleanwine_test)
    pt_fold_error[i, 2] <- mean((cleanwine_test$points - result_pt)^2)
    
    # gbm
    gbmFit_price <- gbm(formula = price ~ ., data = cleanwine_train, 
                  n.trees = 1000, shrinkage = 0.05, interaction.depth = 2, cv.folds = 10, 
                  distribution = "laplace", verbose = FALSE)

    best_iter_price <- gbm.perf(gbmFit_price, method = "cv", plot.it = F)
    gbm_price_pred <- predict(gbmFit_price, newdata = cleanwine_test, n.trees = best_iter_price)
    price_fold_error[i,3] <- mean(abs(cleanwine_test$price - gbm_price_pred))
    
    gbmFit_pt <- gbm(formula = points ~ ., data = cleanwine_train, 
                  n.trees = 1000, shrinkage = 0.05, interaction.depth = 2, cv.folds = 10, 
                  distribution = "laplace", verbose = FALSE) 

    best_iter_pt <- gbm.perf(gbmFit_pt, method = "cv", plot.it = F)
    gbm_pt_pred <- predict(gbmFit_pt, newdata = cleanwine_test, n.trees = best_iter_pt)
    pt_fold_error[i,3] <- mean((cleanwine_test$points - gbm_pt_pred)^2)
    
    # glmnet
    # trn.mtx <- model.matrix(~.,cleanwine_train)
    # trn.smtx <- Matrix(trn.mtx,sparse=T)[,-1]
    # 
    # tst.mtx <- model.matrix(~.,cleanwine_test)
    # tst.smtx <- Matrix(tst.mtx,sparse=T)[,-1]
    
    fit.lasso.price <- cv.glmnet(x=train.data.price,cleanwine_train$price,alpha = 1,type.measure = "mae") 
    l.err.price <- predict(fit.lasso.price,newx = test.data.price,type = 'response')
    price_fold_error[i,4] <- mean(abs(cleanwine_test$price - l.err.price))
 
    fit.ridge.price <- cv.glmnet(x=train.data.price,cleanwine_train$price,alpha=0,type.measure = "mae")
    r.err.price <- predict(fit.ridge.price,newx = test.data.price, type = 'response')
    price_fold_error[i,5] <- mean(abs(cleanwine_test$price - r.err.price))
    
    fit.lasso.pt <- cv.glmnet(x=train.data.pt,cleanwine_train$points,alpha = 1,type.measure = "mse") 
    l.err.pt <- predict(fit.lasso.pt,newx = test.data.pt,type = 'response')
    pt_fold_error[i,4] <- mean((cleanwine_test$points - l.err.pt)^2)
 
    fit.ridge.pt <- cv.glmnet(x=train.data.pt,cleanwine_train$points,alpha=0,type.measure = "mse")
    r.err.pt <- predict(fit.ridge.pt,newx = test.data.pt, type = 'response')
    pt_fold_error[i,5] <- mean((cleanwine_test$points - r.err.pt)^2)
}
```

```{r}
colnames(price_fold_error) <- c("random_forest", "svm", "gbm", "lasso", "ridge")
colnames(pt_fold_error) <- c("random_forest", "svm", "gbm", "lasso", "ridge")
price_fold_error
pt_fold_error
```

```{r}
# clean_train
clean_train <- train[lapply(train, function(x) sum(is.na(x)) / length(x))  < 0.1]
clean_train <- clean(clean_train)
clean_train <- clean_train %>% select(-title, -country, -province)
clean_train <- clean_train %>% select(-Scaled_Points, -Percentile_Points)
dim(clean_train)

# pick best model and predict on test
clean_test <- test[lapply(test, function(x) sum(is.na(x)) / length(x) ) < 0.1]
clean_test <- clean(clean_test)
clean_test_country <- clean_test$country
clean_test_province <- clean_test$province
clean_test <- clean_test %>% select(-title, -country, -province)
clean_test <- clean_test %>% select(-Scaled_Points, -Percentile_Points)
dim(clean_test)
# test.data.price <- test %>% select(-price)
# test.data.price <- sparse.model.matrix(~., test.data.price)[,-1]
# test.data.pt <- test %>% select(-points)
# test.data.pt <- sparse.model.matrix(~., test.data.pt)[,-1]
    
svm_test_price <- svm(price~., clean_train)
svm_test_pt <- svm(points~., clean_train)
result_test_price <- predict(svm_test_price, clean_test)
mean(abs(clean_test$price - result_test_price))

result_test_pt <- predict(svm_test_pt, clean_test)
mean((clean_test$points - result_test_pt)^2)

clean_test$country <- clean_test_country
clean_test$province <- clean_test_province
clean_test$price_pred <- result_test_price
clean_test$point_pred <- result_test_pt

```

```{r}
write_csv(clean_test, "clean_test.csv")
```

```{r}
price_pt_df <- data.frame(cbind(clean_test$points, clean_test$price, result_test_price, result_test_pt))
colnames(price_pt_df) <- c("points", "price", "pred_price", "pred_point")
ggplot(aes(x=points, y=price), data = price_pt_df) + geom_jitter() + geom_point(aes(x=points, y=pred_price), col="red")
ggplot(aes(x=price, y=points), data = price_pt_df) + geom_jitter() + geom_point(aes(x=price, y=pred_point), col="red")
```

```{r}
save(clean_train, clean_test, price_fold_error, pt_fold_error, file = "~/Dropbox/Duke/707/Project/707Wine/wine_models.RData")
```


```{r}
# test
cleanwine <- data
cleanwine$location <- factor(cleanwine$location)
cleanwine$taster_name <- factor(cleanwine$taster_name)
cleanwine$title <- factor(cleanwine$title)
cleanwine$variety <- factor(cleanwine$variety)
cleanwine$taster_name <- addNA(cleanwine$taster_name)
cleanwine$region_1 <- factor(cleanwine$region_1)
cleanwine$region_2 <- factor(cleanwine$region_2)

cleanwine <- cleanwine[lapply(cleanwine, function(x) sum(is.na(x)) / length(x) ) < 0.1]
cleanwine <- clean(cleanwine)
cleanwine <- cleanwine %>% select(-title, -country)
summary(cleanwine)

```
```{r}

tmp = data #%>% select(-Scaled_Points, -Percentile_Points)

train.idx <- sample(nrow(tmp), 4/5 * nrow(tmp))
cleanwine_train <- tmp[train.idx, ]
cleanwine_test <- tmp[-train.idx, ]

cleanwine_train$location <- factor(cleanwine_train$location)
    cleanwine_train$taster_name <- factor(cleanwine_train$taster_name)
    cleanwine_train$taster_name <- addNA(cleanwine_train$taster_name)
    cleanwine_train$title <- factor(cleanwine_train$title)
    cleanwine_train$variety <- factor(cleanwine_train$variety)
    cleanwine_train$region_1 <- factor(cleanwine_train$region_1)
    cleanwine_train$region_2 <- factor(cleanwine_train$region_2)
    
    cleanwine_test$location <- factor(cleanwine_test$location)
    cleanwine_test$taster_name <- factor(cleanwine_test$taster_name)
    cleanwine_test$taster_name <- addNA(cleanwine_test$taster_name)
    cleanwine_test$title <- factor(cleanwine_test$title)
    cleanwine_test$variety <- factor(cleanwine_test$variety)
    cleanwine_test$region_1 <- factor(cleanwine_test$region_1)
    cleanwine_test$region_2 <- factor(cleanwine_test$region_2)

    cleanwine_train <- cleanwine_train[lapply(cleanwine_train, function(x) sum(is.na(x)) / length(x) ) < 0.1]
    cleanwine_train <- clean(cleanwine_train)
    cleanwine_train <- cleanwine_train %>% select(-title, -country)
    print(colnames(cleanwine_train))
    
    cleanwine_test <- cleanwine_test[lapply(cleanwine_test, function(x) sum(is.na(x)) / length(x) ) < 0.1]
    cleanwine_test <- clean(cleanwine_test)
    cleanwine_test <- cleanwine_test %>% select(-title, -country)
    print(colnames(cleanwine_test))
    
    cleanwine_train <- cleanwine_train %>% select(-Scaled_Points, -Percentile_Points)
    train.data.price <- cleanwine_train %>% select(-price)
    print(colnames(train.data.price))
    train.data.price <- sparse.model.matrix(~., train.data.price)[,-1]
    train.data.pt <- cleanwine_train %>% select(-points)
    train.data.pt <- sparse.model.matrix(~., train.data.pt)[,-1]
    
    cleanwine_test <- cleanwine_test %>% select(-Scaled_Points, -Percentile_Points)
    test.data.price <- cleanwine_test %>% select(-price)
    print(colnames(test.data.price))
    test.data.price <- sparse.model.matrix(~., test.data.price)[,-1]
    print(colnames(test.data.price))
    test.data.pt <- cleanwine_test %>% select(-points)
    test.data.pt <- sparse.model.matrix(~., test.data.pt)[,-1]
```

```{r}
# tmp = cleanwine %>% select(-Scaled_Points, -Percentile_Points)
# 
# train.idx <- sample(nrow(tmp), 4/5 * nrow(tmp))
# tmp.train <- tmp[train.idx, ]
# tmp.test <- tmp[-train.idx, ]
# train.data.price <- tmp.train %>% select(-price)
# train.data.price <- sparse.model.matrix(~., train.data.price)[,-1]
# print(colnames(train.data.price))
# train.data.pt <- tmp.train %>% select(-points)
# train.data.pt <- sparse.model.matrix(~., train.data.pt)[,-1]
# test.data.price <- tmp.test %>% select(-price)
# test.data.price <- sparse.model.matrix(~., test.data.price)[,-1]
# print(colnames(test.data.price))
# test.data.pt <- tmp.test %>% select(-points)
# test.data.pt <- sparse.model.matrix(~., test.data.pt)[,-1]

subsamps <- seq(0.1, 1, 0.1)
colsamps <- seq(0.1, 1, 0.1)
#train_error <- matrix(NA, nrow = length(seq(0.1, 1, 0.1)), ncol = length(seq(0.1, 1, 0.1)))
train_error_price <- vector("numeric", length(seq(0.1, 1, 0.1)))
train_error_pt <- vector("numeric", length(seq(0.1, 1, 0.1)))
for (i in 1:length(seq(0.1, 1, 0.1))) {
  #for (j in 1:length(seq(0.1, 1, 0.1))) {
    rf_cleanwine_price <- xgboost(data = train.data.price, label=cleanwine_train$price, verbose = 0, max_depth = 5, num_parallel_tree = 1000, subsample = subsamps[i], nrounds = 1, colsample_bylevel=0.6, objective = "reg:linear", eval_metric = 'mae')
    rf_cleanwine_pt <- xgboost(data = train.data.pt, label=cleanwine_train$points, verbose = 0, max_depth = 5, num_parallel_tree = 1000, subsample = subsamps[i], nrounds = 1, colsample_bylevel=0.6, objective = "reg:linear", eval_metric = 'rmse')
    #train_error[i,j] <- as.numeric(rf_cleanwine$evaluation_log[,2])
    train_error_price[i] <- as.numeric(rf_cleanwine_price$evaluation_log[,2])
    train_error_pt[i] <- as.numeric(rf_cleanwine_pt$evaluation_log[,2])
  #}
}
min.index.price <- which(train_error_price == min(train_error_price), arr.ind = TRUE)
min.index.pt <- which(train_error_pt == min(train_error_pt), arr.ind = TRUE)
rf_cleanwine_price <- xgboost(data = train.data.price, label=cleanwine_train$price, max_depth = 0, verbose = 0, num_parallel_tree = 1000, subsample = subsamps[min.index.price], nrounds = 1, colsample_bylevel=0.6, objective = "reg:linear", eval_metric = 'mae')
print(rf_cleanwine_price$feature_names)
rf_cleanwine_pt <- xgboost(data = train.data.pt, label=cleanwine_train$points, max_depth = 0, verbose = 0, num_parallel_tree = 1000, subsample = subsamps[min.index.pt], nrounds = 1, colsample_bylevel=0.6, objective = "reg:linear", eval_metric = 'rmse')

test.pred.price <- predict(rf_cleanwine_price, test.data.price)
mean(abs(test.pred.price - tmp.test$price))

test.pred.pt <- predict(rf_cleanwine_pt, test.data.pt)
mean((test.pred.pt - tmp.test$points)^2)
```

```{r}
which(train_error == min(train_error), arr.ind = TRUE)
```
```{r}
#gammalist <- c(0.005,0.01,0.015,0.02,0.025,0.03,0.035,0.04,0.045,0.05)
#tune.out <- tune.svm(tmp.data, tmp$price, 
                 #kernel='linear', cost=2^(-1:5), gamma = gammalist)
#summary(tune.out)

svm_cleanwine_price <- svm(price~., tmp.train)
svm_cleanwine_price

svm_cleanwine_pt <- svm(points~., tmp.train)
svm_cleanwine_pt
```
```{r}
result_price <- test(svm_cleanwine_price, tmp.test)
mean(abs(tmp$price - result_price))

result_pt <- test(svm_cleanwine_pt, tmp.test)
mean((tmp$points - result_pt)^2)
```



```{r}
## Split in training and test data
train.idx <- sample(nrow(iris), 2/3 * nrow(iris))
iris.train <- iris[train.idx, ]
iris.test <- iris[-train.idx, ]

## Run case-specific RF
csrf(Species ~ ., training_data = iris.train, test_data = iris.test, 
     params1 = list(num.trees = 50, mtry = 4), 
     params2 = list(num.trees = 5))
```


```{r}
#idx = sample(1:900)
tmp_train = tmp[1:900, ]
tmp_test  = tmp[901:1000, ]

rf_cleanwine <- csrf(sparse.model.matrix(tmp_train %>% select(-price)), tmp_train$price, 
                     params1 = list(num.trees = 500, mtry = 4), 
                     params2 = list(num.trees = 50, mtry = 4))
```


```{r}
rf_cleanwine <- csrf(price ~ ., cleanwine %>% select(-Scaled_Points), params1 = list(num.trees = 50, mtry = 4))
```



```{r}
# gbm
gbmFit <- gbm(formula = price ~ ., data = cleanwine_price_10perc %>% select(-title, -winery), 
              n.trees = 1000, shrinkage = 0.01, interaction.depth = 2, cv.folds = 10, 
              distribution = "gaussian")

best_iter <- gbm.perf(gbmFit, method = "cv")

# Performance on whole dataset

diff_squared <- (cleanwine_price_10perc$price - 
    predict(gbmFit, newdata = cleanwine_price_10perc, n.trees = best_iter))^2

mean(diff_squared, na.rm = TRUE)

```
```{r}
# ranger
csrf_wine <- csrf(formula = price ~ ., training_data = cleanwine_price_train, test_data = cleanwine_price_test, params1 = list(num.trees = 50, mtry = 4), params2 = list(num.trees = 5))
csrf_wine
```


```{r}
# random forest
dat.cleanwine <- sparse.model.matrix(~., data = cleanwine_price_10perc %>% select(-title, -winery))[,-1]
price <- cleanwine_price_10perc$price

rf_wine <- randomForest(as.matrix(dat.cleanwine), price, do.trace = F, 
                          importance = T) 
rf_wine
#oob_wine <- mean(price - rf_wine$votes[,2])^2)
```

